<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Branch extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'user_id', 'branch_type_id', 'name'
        ];

    public function toArray()
    {
        $this->load('images');
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['type'] = $this->branchType;
        return $array;
    }


    public function branchType() {
        return $this->belongsTo('App\BranchType', 'branch_type_id');
    }

    public function images() {
        return $this->hasMany('App\Image');
    }
}
