<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes;
    protected  $fillable = [
        'user_id',
        'division_id',
        'parent_category'
        ];

    public function toArray()
    {
        $this->load(array('countries', 'languages', 'childrenCategories'));
        $array = parent::toArray();
        return $array; // TODO: Change the autogenerated stub
    }

    public function division() {
        return $this->belongsTo('App\Division');
    }

    public function countries() {
        return $this->belongsToMany('App\Country', "category_country");
    }

    public function languages() {
        return $this->hasMany('App\CategoryLanguage');
    }

    public function parentCategory() {
        return $this->belongsTo(self::class, 'parent_category');
    }
//
    public function childrenCategories() {
        return $this->hasMany(self::class, 'parent_category');
    }

}
