<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DivisionContent extends Model
{
    protected $table = 'divisions_content';
    protected $fillable = ['name', 'division_id', 'language_id'];
    protected $hidden = ['language_id'];

    public function toArray()
    {
//        $this->load('language');
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['language'] = $this->language->name;
        return $array;
    }

    public function division() {
        return $this->belongsTo('App\Division');
    }

    public function language() {
        return $this->belongsTo('App\Language');
    }
}
