<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Division extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'user_id'
    ];

    public function toArray()
    {
        $this->load(array('divisionContent', 'countries'));
        $array = parent::toArray();
        return $array; // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function divisionContent() {
        return $this->hasMany('App\DivisionContent');
    }

    public function countries() {
        return $this->belongsToMany('App\Country');
    }
}
