<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductType extends Model
{
    protected $table = 'types';

    protected $fillable = [
        'user_id'
    ];

    public function toArray()
    {
        $this->load('productTypeContents');
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    public function products() {
        return $this->hasMany('App\Product');
    }

    public function productTypeContents() {
        return $this->hasMany('App\ProducTypeLanguages', 'type_id');
    }
}
