<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProducTypeLanguages extends Model
{
    protected $table = 'types_content';

    protected $fillable = [
        'name',
        'type_id',
        'language_id'
    ];

    protected $hidden = [
        'language_id'
    ];

    public function toArray()
    {
        $array = parent::toArray(); // TODO: Change the autogenerated stub
        $array['language'] = $this->language->name;
        return $array;
    }

    public function language() {
        return $this->belongsTo('App\Language');
    }

    public function productType() {
        return $this->belongsTo('App\ProductType');
    }
}
