<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $table = 'tags';

    protected $fillable = [
        'user_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tagContent()
    {
        return $this->hasMany(TagContent::class);
    }

    public function toArray()
    {
        $this->load('tagContent');
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

}

