<?php

namespace App;

use App\Tag;
use App\Language;
use Illuminate\Database\Eloquent\Model;

class TagContent extends Model
{
    protected $table = 'tags_content';

    protected $fillable = [
        'name',
        'tag_id',
        'language_id'
    ];

    protected $hidden = [
        'language_id'
    ];

    public function tag() {
        return $this->belongsTo(Tag::class);
    }

    public function language() {
        return $this->belongsTo('App\Language');
    }

    public function toArray()
    {
        $this->load('language');
        return parent::toArray(); // TODO: Change the autogenerated stub
    }
}
